export default {
  UPDATE_STORE: 'UPDATE_STORE',
  REQUESTED_FAILED: 'REQUESTED_FAILED',
  REQUESTED_START: 'REQUESTED_START',
  REQUESTED_SUCCEEDED: 'REQUESTED_SUCCEEDED',
  UPDATE_BREAD_LIST: 'UPDATE_BREAD_LIST',

  SET_EDIT_STATUS: 'SET_EDIT_STATUS',
  UPDATE_AMEND_VALUE: 'UPDATE_AMEND_VALUE',
  CLEAN_AMEND_VALUE: 'CLEAN_AMEND_VALUE'
};
