export default {
  UPDATE_STORE: 'GET_CATEGORIES',
  REQUESTED_FAILED: 'REQUESTED_FAILED',
  REQUESTED_START: 'REQUESTED_START',
  REQUESTED_SUCCEEDED: 'REQUESTED_SUCCEEDED',
  UPDATE_BREAD_LIST: 'UPDATE_BREAD_LIST',
  GET_LIST: 'GET_LIST',
  GET_POST: 'GET_POST'
};
