export default {
  GET_CATEGORIES: 'GET_CATEGORIES',
  REQUESTED_FAILED: 'REQUESTED_FAILED',
  REQUESTED_START: 'REQUESTED_START',
  REQUESTED_SUCCEEDED: 'REQUESTED_SUCCEEDED',
  GET_LIST: 'GET_LIST',
  GET_POST: 'GET_POST'
};
