export default {
  UPDATE_STORE: 'UPDATE_STORE',
  REQUESTED_FAILED: 'REQUESTED_FAILED',
  REQUESTED_START: 'REQUESTED_START',
  REQUESTED_SUCCEEDED: 'REQUESTED_SUCCEEDED',
  UPDATE_BREAD_LIST: 'UPDATE_BREAD_LIST',
  FILTER_RULES_CHANGE: 'FILTER_RULES_CHANGE'
};
