import authTypes from './Auth/Types';
export default {
  SET_EDIT_STATUS: 'SET_EDIT_STATUS',
  UPDATE_AMEND_VALUE: 'UPDATE_AMEND_VALUE',
  CLEAN_AMEND_VALUE: 'CLEAN_AMEND_VALUE',
  FILTER_RULES_CHANGE: 'FILTER_RULES_CHANGE',
  ...authTypes
};
